title: Техническое решение
remote_theme: just-the-docs/just-the-docs
lang: ru
search_enabled: true
aux_links:
  "Репозиторий на GitHub":
    - "https://github.com/spbu-ds-practicum-2025/example-project"
just_the_docs:
  includes:
    head_custom: head_custom.html
